[package]
name = "daf-yomi"
version = "2.0.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-storage = "0.3.0"
leptos = "0.8.12"
reqwest = "0.12.23"
serde = { version = "1.0.228", features = ["serde_derive"] }
wasm-bindgen = "=0.2.104"
